# Generated by Django 3.2.6 on 2021-08-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='PhoneNumber',
            field=models.CharField(default='admin', max_length=20),
            preserve_default=False,
        ),
    ]
