# Generated by Django 3.2.6 on 2021-08-29 15:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20210829_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='SMSCreatedTime',
            field=models.TimeField(default=datetime.datetime(2021, 8, 29, 15, 41, 5, 188037, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
