# Generated by Django 3.2.6 on 2021-08-30 17:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_auto_20210829_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='SMSCreatedTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 30, 17, 14, 52, 61006, tzinfo=utc)),
        ),
    ]
