# Generated by Django 3.2.6 on 2021-09-11 09:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0016_alter_customuser_smscreatedtime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('is_shop', 'can access to shop panel to add or change product')]},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='SMSCreatedTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 11, 9, 33, 9, 911313, tzinfo=utc)),
        ),
    ]
