# Generated by Django 3.2.6 on 2021-09-11 09:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0018_auto_20210911_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('is_shop', 'can access to shop panel to add or change product')]},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='SMSCreatedTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 11, 9, 38, 0, 664072, tzinfo=utc)),
        ),
    ]
