# Generated by Django 3.2.6 on 2021-09-12 18:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0019_auto_20210911_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='SMSCreatedTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 12, 18, 48, 46, 213317, tzinfo=utc)),
        ),
    ]
