# Generated by Django 3.2.6 on 2021-09-16 06:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0022_auto_20210915_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='SMSCreatedTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 6, 34, 10, 287429, tzinfo=utc)),
        ),
    ]
