# Generated by Django 3.2.6 on 2021-09-16 06:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ShopAccount', '0004_remove_shopaccount_touseraccount'),
        ('Account', '0023_alter_customuser_smscreatedtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ToShopAccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ShopAccount.shopaccount'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='SMSCreatedTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 6, 44, 5, 266992, tzinfo=utc)),
        ),
    ]
