# Generated by Django 3.2.6 on 2021-08-30 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ShopAccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Writer', models.CharField(max_length=150)),
                ('Translator', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SubProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.IntegerField()),
                ('Number', models.SmallIntegerField()),
                ('ToProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
                ('ToShop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopAccount.shopaccount')),
            ],
        ),
    ]
