# Generated by Django 3.2.6 on 2021-08-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Translator',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
