# Generated by Django 3.2.6 on 2021-09-02 12:44

import Product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_product_translator'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Image',
            field=models.ImageField(default='None.jpg', upload_to=Product.models.product_image_name),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Publisher',
            field=models.CharField(default='nodo', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Slug',
            field=models.SlugField(allow_unicode=True, blank=True),
        ),
    ]
