# Generated by Django 3.2.6 on 2021-09-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20210902_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
