# Generated by Django 3.2.6 on 2021-09-02 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_auto_20210903_0024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ProductCategory',
        ),
    ]
