# Generated by Django 3.2.6 on 2021-09-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproduct',
            name='IsSecondHand',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='SecondHandRate',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=2),
        ),
    ]
