# Generated by Django 3.2.6 on 2021-09-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_auto_20210915_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproduct',
            name='SellOnline',
            field=models.BooleanField(default=True),
        ),
    ]
