# Generated by Django 3.2.6 on 2021-09-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_auto_20210916_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ToCategory',
            field=models.ManyToManyField(blank=True, null=True, to='Product.ProductCategory'),
        ),
    ]
