# Generated by Django 3.2.6 on 2021-09-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_product_onelinedescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproduct',
            name='SecondHandRate',
            field=models.CharField(choices=[('N', 'N'), ('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=2),
        ),
    ]
