# Generated by Django 3.2.6 on 2021-09-07 12:22

import SiteSetting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title1', models.CharField(max_length=50)),
                ('title2', models.CharField(max_length=50)),
                ('Button', models.CharField(max_length=50)),
                ('Color', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to=SiteSetting.models.home_slider_image_name)),
            ],
        ),
    ]
