# Generated by Django 3.2.6 on 2021-09-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetting', '0002_rename_title2_homeslider_title2'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='Active',
            field=models.BooleanField(default=False),
        ),
    ]
