# Generated by Django 3.2.6 on 2021-09-11 09:33

import ShopAccount.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopAccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopaccount',
            name='Address',
            field=models.CharField(default=' ', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopaccount',
            name='Contact',
            field=models.CharField(default=' ', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopaccount',
            name='Image',
            field=models.ImageField(default='1.jpg', upload_to=ShopAccount.models.shop_image_name),
            preserve_default=False,
        ),
    ]
