# Generated by Django 3.2.6 on 2021-09-16 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopAccount', '0003_shopaccount_touseraccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopaccount',
            name='ToUserAccount',
        ),
    ]
