# Generated by Django 3.2.6 on 2021-09-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='ReceiverPhoneNumber',
            field=models.CharField(default=' ', max_length=11),
            preserve_default=False,
        ),
    ]
