# Generated by Django 3.2.6 on 2021-09-20 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_shippingaddress_receiverphonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='ReceiverPhoneNumber',
        ),
    ]
